In [4]:
%matplotlib inline
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

from pandas import set_option ##
set_option("display.max_rows", 16)

LARGE_FIGSIZE = (12, 8)

In [5]:
##It launchs a qtconsole window connected to this (same) kernel
#%qtconsole

In [235]:
def file_name_to_date(data_file):
    date = '-'.join(file1.split('.')[0].split('_')[3:5])
    date = pd.to_datetime(date) #Timestamp type
    return date

file1='Alumnos_con_Cursos13_20161018_1028.csv'
d = file_name_to_date(file1)    
print(d,type(d))

2016-10-18 10:28:00 <class 'pandas.tslib.Timestamp'>

In [231]:
def df_maker(data_file):
    table=pd.read_table(data_file, sep=',', encoding='latin1')
    
    date = file_name_to_date(data_file)
    date_col = [date for i in range(table.shape[0])] #future date column
    date_series = pd.Series(date_col)
    
    table.loc[:,'date'] = pd.Series(date_col)#Adding a new Timestamp column named 'date' 
    table.set_index('date', inplace=True) #making it the index (useful??)
    
    return table


test_table = df_maker(file1)
test_table

,nombre,curso,horario,sala
date,,,,
2016-10-18 10:28:00,"Abarca Brown, Joaquin Esteban",MT21.001,Lun 17:30,4
2016-10-18 10:28:00,"Abarca Brown, Joaquin Esteban",MT22.001,Lun 19:00,4
2016-10-18 10:28:00,"Abarca Brown, Joaquin Esteban",LC21.004,Vie 17:30,7
2016-10-18 10:28:00,"Abarca Brown, Joaquin Esteban",LC22.004,Vie 19:00,7
2016-10-18 10:28:00,"Aburto Aburto, Patricia Belen",M311.001,Vie 16:00,12
2016-10-18 10:28:00,"Aburto Aburto, Patricia Belen",L311.001,Vie 17:30,12
2016-10-18 10:28:00,"Aburto Bustos, Leonardo",CB31.002,Jue 11:30,2
2016-10-18 10:28:00,"Aburto Bustos, Leonardo",CB32.001,Jue 10:00,2
...,...,...,...,...
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",CB33.007,Mar 13:00,7
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",QM11.001,Vie 19:00,10
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EM31.009,Jue 08:30,8
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EM32.009,Jue 10:00,8
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EM33.009,Jue 11:30,8
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EL31.008,Lun 08:30,4
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EL32.008,Lun 10:00,4
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",EL33.008,Lun 11:30,4

## Querying test

In [233]:
##works
#test_table[(table2["curso"] == "CB31.006") & (table2["sala"]== 7)]
##works too, cleaner
test_table[(test_table.curso == "CB31.006") & (test_table.sala == 7)]

,nombre,curso,horario,sala
date,,,,
2016-10-18 10:28:00,"Acuña Imio, Felipe Andres",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Aguilar Brulé, Fernanda Catalina",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Alarcón Almonacid, Paulina Belén",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Almonacid Vidal, Francisco Javier",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Alvarado Soto, Francisca María José",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Birke Santana, Maritza Roxana",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Calisto Rodriguez, Francisca Natalia",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Carcamo Borquez, Maria Jose",CB31.006,Mar 10:00,7
...,...,...,...,...
2016-10-18 10:28:00,"Sepulveda Duncker, Jennifer Waleska",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Ulloa Navarro, Priscilla",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Velasquez Chavez, Mathias",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Velasquez Zuñiga, Claudio Daniel Alejandro",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Vera Saldivia, Aira Denis",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Vicencio Yañez, Catalina Leonor",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Vivar Venegas, Yalin Escarlett",CB31.006,Mar 10:00,7
2016-10-18 10:28:00,"Zuñiga Zavala, Bastian Fernando",CB31.006,Mar 10:00,7